#!/usr/bin/env python3
"""Bundle the browser worker and its unchanged WASM binaries into one request."""
import argparse
import base64
from pathlib import Path


def build(root):
    scripts = ['vendor/edmonds/edmonds.js', 'vendor/rapidnj/rapidnj.js',
               'browser-backend.js', 'edmonds-worker.js']
    parts = [
        '// Generated by build-worker.py; edit the source files, then rebuild.\n'
        '// GrapeTree: GPL-3.0-or-later; RapidNJ: GPL-2.0. See LICENSE and THIRD_PARTY.md.\n'
        'self.GRAPETREE_BUNDLED = true;\n'
        'self.GRAPETREE_WORKER_URL = self.location.href;\n'
        'self.GRAPETREE_WASM_BINARIES = {};\n'
    ]
    for name, relative in [('edmonds', 'vendor/edmonds/edmonds.wasm'),
                           ('rapidNJ', 'vendor/rapidnj/rapidnj.wasm')]:
        encoded = base64.b64encode((root / relative).read_bytes()).decode('ascii')
        parts.append(f'self.GRAPETREE_WASM_BINARIES.{name} = '
                     f'Uint8Array.from(atob("{encoded}"), c => c.charCodeAt(0));\n')
    for source in scripts:
        parts.append(f'\n// Source: {source}\n')
        parts.append((root / source).read_text() + '\n;\n')
    return ''.join(parts)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the committed bundle is stale')
    args = parser.parse_args()
    root = Path(__file__).resolve().parent
    destination = root / 'runtime-worker.js'
    content = build(root)
    if args.check:
        if not destination.exists() or destination.read_text() != content:
            parser.exit(1, 'Stale browser worker: run python browser-wasm/build-worker.py\n')
        print('Browser worker bundle matches its source files and WASM binaries.')
    else:
        destination.write_text(content)
        print(f'Built {destination.name} ({len(content.encode())} bytes)')


if __name__ == '__main__':
    main()
